- name: "Fetch kops binary"
  get_url:
    url: "{{ kops_download_url }}"
    dest: "{{ kops_download_path }}/{{ kops_bin }}"
    timeout: 30

- name: "Move kops bin to kops_bin_basepath"
  become: yes
  command: mv {{ kops_download_path }}/{{ kops_bin }} {{ kops_bin_basepath }}

- name: "Make kops bin executable"
  become: yes
  file: 
    path: "{{ kops_bin_basepath }}/{{ kops_bin }}"
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g-wx,o-rwx
  