- name: "Download and Unzip helm .tar and move to $PATH"
  unarchive: 
    src: "{{ helm_url }}"
    dest: "{{ helm_download_path }}"
    remote_src: yes
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: "Move helm executable to /usr/local/bin"
  become: yes
  command: mv {{ helm_download_path }}/linux-amd64/{{ helm_bin }} {{ helm_bin_basepath }}

- name: "Install Chart repo"
  shell: "helm repo add stable https://kubernetes-charts.storage.googleapis.com/"


  
