- name: "Check SSH key exists for ec2-user"
  stat: path="{{ current_user_home }}/.ssh/id_rsa.pub
  register: ssh_key_exists_stat

- name: "Create SSH keys if not present"
  command: ssh-keygen -q -t -f {{current_user_home}}/.ssh/id_rsa rsa -C "" -N ""
  args:
    creates: "{{ current_user_home }}/.ssh/id_rsa.pub"
  when: ssh_key_exists_stat.stat.exists == False

- name: "Check kops binary is present or not"
  stat: path="{{ kops_bin_basepath }}/{{ kops_bin }}"
  register: kops_bin_stat

- name: "Check kubectl binary is present or not"
  stat: path="{{ kubectl_bin_basepath }}/{{ kubectl_bin }}"
  register: kubectl_bin_stat

- include_tasks: install_kops.yml
  when: kops_bin_stat.stat.exists == False

- include_tasks: install_kubectl.yml
  when: kubectl_bin_stat.stat.exists == False

- name: "Create directory to pull iac code"
  become: yes
  file:
    path: "{{ iac_repo_dest }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: "Install git"
  become: yes
  yum:
    name: git
    state: present

- name: "Pull latest code from memgen/k8s repository"
  git:
    repo: "https://github.com/shubhamoli/iac.git"
    dest: "{{ iac_repo_dest }}"
    clone: yes
    update: yes

- name: "Check if cluster config exists"
  stat: path="{{ iac_repo_dest }}/k8s/kops-cluster-memegen.yml"
  register: cluster_config_stat

- include_tasks: create-cluster.yml
  when: cluster_config_stat.stat.exists == False 
