---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana
  namespace: monitoring-prod
  labels:
    grafana_datasource: '1'      # for prometheus
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server.monitoring.svc.cluster.local
