---
- name: "Add jenkins repository"
  become: yes
  get_url:
      url: {{ jenkins_repo_url }}
      dest: {{ jenkins_repo_path }}

- name: "Add jenkins-ci key file"
  become: yes
  rpm_key:
    state: present
    key: {{ jenkins_key_file_url }}
  
- name: "Finally, install Jenkins"
  become: yes
  yum:
    name: jenkins
    state: present
  
- name: "Start Jenkins Server"
  notify: restart-jenkins-server


- name: "Print Admin Pass to unlock jenkins"
  slurp:
    src:  {{ jenkins_home }}/secrets/initialAdminPassword
  register: admin_pass

- debug:
    msg: "{{ admin_pass['stdout'] }}"

- name: "Set jenkins password as variable"
  set_fact:
    jenkins_admin_password: "{{ admin_pass['stdout'] }}"
  no_log: true
