
kops_version: 1.14.1
kops_download_url: https://github.com/kubernetes/kops/releases/download/{{kops_version}}/kops-linux-amd64

kubectl_version: v1.16.2
kubectl_download_url: https://storage.googleapis.com/kubernetes-release/release/{{kubectl_version}}/bin/linux/amd64/kubectl

kops_download_path: /tmp
kubectl_download_path: /tmp

kops_bin: kops
kubectl_bin: kubectl

kops_bin_basepath: /usr/local/bin/
kubectl_bin_basepath: /usr/local/bin/

iac_repo_dest: /opt/apps