
kops_version: 1.14.1
kops_download_url: https://github.com/kubernetes/kops/releases/download/{{kops_version}}/kops-linux-amd64

kubectl_version: v1.16.2
kubectl_download_url: https://storage.googleapis.com/kubernetes-release/release/{{kubectl_version}}/bin/linux/amd64/kubectl

kops_download_path: /tmp
kubectl_download_path: /tmp

kops_bin: kops
kubectl_bin: kubectl

kops_bin_basepath: /usr/local/bin/
kubectl_bin_basepath: /usr/local/bin/

iac_repo_dest: /opt/apps

## cluster specific default settings

cluster_name: memegen-prod.k8s.local
cluster_state_store: s3://memegen-kops-cluster-state
cluster_region: ap-south-1
cluster_topology: private
cluster_cnp: calico
cluster_state_local_file: kops-cluster-memegen

cluster_master_zones: ap-south-1a
cluster_AZs: ap-south-1a,ap-south-1b

cluster_worker_node_count: 2
cluster_master_node_count: 1

cluster_master_node_type: t3.small
cluster_worker_node_type: t3.small

cluster_worker_node_vol_size: 50
cluster_master_node_vol_size: 50

cluster_setup_bastion: "false"
cluster_cloud_labels: "Team=DevOps,Owner=Shubham-Oli,ManagedBy=k8s"

helm_version: "v3.0.0"
helm_bin: "helm"
helm_url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
helm_download_path: "/tmp/"
helm_bin_basepath: /usr/local/bin/