# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: memegen-prod
#   name: db-svc
# spec:
#   ports:
#     - name: "db"
#       protocol: TCP
#       port: 5432
#       targetPort: 5432

# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   namespace: memegen-prod
#   name: db-svc
# subsets:
#   - addresses:
#       - ip: 127.0.0.1
#     ports:
#       - port: 5432
#         name: "db"
