---

jenkins_version: 2.190.2

jenkins_war_name: jenkins.war

jenkins_repo_url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo

jenkins_repo_path: /etc/yum.repos.d/jenkins.repo

jenkins_key_file_url: https://pkg.jenkins.io/redhat/jenkins.io.key

jenkins_home: /var/lib/jenkins

jenkins_hostname: localhost

jenkins_port: 8080

jenkins_admin_username: admin

jenkins_plugins: ["build-timeout", 
                  "credentials-binding", 
                  "timestamper", 
                  "pipeline-stage-view", 
                  "pipeline",
                  "blueocean",
                  "git", 
                  "ssh-slaves", 
                  "matrix-auth", 
                  "mailer", 
                  "docker-workflow",
                  "kubernetes-cd",       # official K8s plugin for CD in k8s cluster
                  "ssh-agent",
                  "ssh",
                  "ws-cleanup",
                  "workflow-aggregator",    # pipeline plugin
                  "build-pipeline-plugin"
]

jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_state: enabled
jenkins_updates_url: "https://updates.jenkins.io"
jenkins_plugins_install_dependencies: true